services:
  ## KAFKA
  kafka:
      image: confluentinc/cp-kafka:latest
      container_name: kafka
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_BROKER_ID: 1
        KAFKA_PROCESS_ROLES: 'broker,controller'
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
        KAFKA_LISTENERS: 'PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093'
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
        KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_DEFAULT_REPLICATION_FACTOR: 1 # we are just making a POC so no need for replications 
        KAFKA_MIN_INSYNC_REPLICAS: 1 # see above
      ports:
        - "9092:9092"
      networks:
        - kafka-net
  ## GATEWAY
  gateway:
    build: ./gateway-app-service
    depends_on:
      - user-service
      - catalogue-service
      - payment-service
      - auction-service
    ports:
      - "8080:8080" # expose to host
    networks:
      - backend-net
  # USER SERVICE
  user-service:
     build:
       context: ./user-app-service
       dockerfile: Dockerfile
     depends_on:
       - user-db
     environment:
       SPRING_DATA_MONGODB_URI: mongodb://root:secret@user-db:27017/userdb?authSource=admin
     networks:
        - backend-net
        - kafka-net

  user-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: userdb
    volumes:
      - user-db:/data/db
      - ./init-scripts/init-userdb.js:/docker-entrypoint-initdb.d/init-userdb.js:ro ## initialize user db
    networks:
      - kafka-net

  # PAYMENT SERVICE
  payment-service:
    build:
      context: ./payment-app-service
      dockerfile: Dockerfile
    depends_on:
      - payment-db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@payment-db:27017/paymentdb?authSource=admin
    networks:
      - backend-net
      - kafka-net

  payment-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: paymentdb
    volumes:
      - payment-db:/data/db
      - ./init-scripts/init-payment.js:/docker-entrypoint-initdb.d/init-paymentdb.js:ro ## initialize user db
    networks:
        - backend-net

  # AUCTION SERVICE #
  auction-service:
    build:
      context: ./auction-app-service
      dockerfile: Dockerfile
    depends_on:
      - auction-db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@auction-db:27017/auctiondb?authSource=admin
    networks:
      - backend-net
      - kafka-net

  auction-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: auctiondb
    volumes:
      - auction-db:/data/db
      - ./init-scripts/init-auctiondb.js:/docker-entrypoint-initdb.d/init-auctiondb.js:ro
    networks:
        - backend-net

  # CATALOGUE SERVICE
  catalogue-service:
    build:
      context: ./catalogue-app-service
      dockerfile: Dockerfile
    depends_on:
      - catalogue-db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@catalogue-db:27017/cataloguedb?authSource=admin
    networks:
      - backend-net
      - kafka-net

  catalogue-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: cataloguedb
    volumes:
      - catalogue-db:/data/db
      - ./init-scripts/init-cataloguedb.js:/docker-entrypoint-initdb.d/init-cataloguedb.js:ro
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
  kafka-net:
    driver: bridge

volumes:
  payment-db:
  user-db:
  auction-db:
  bid-db:
  catalogue-db:
