server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}

#https://stackoverflow.com/questions/43555282/react-js-application-showing-404-not-found-in-nginx-server